FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Injeta variáveis de ambiente no momento do build
ARG VITE_API_URL
ARG VITE_INSTANCE_CLIENT_NAME
ARG VITE_IMG_LOGO_MAIN
ARG VITE_IMG_AGENT_AVATAR_LARGE

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_INSTANCE_CLIENT_NAME=$VITE_INSTANCE_CLIENT_NAME
ENV VITE_IMG_LOGO_MAIN=$VITE_IMG_LOGO_MAIN
ENV VITE_IMG_AGENT_AVATAR_LARGE=$VITE_IMG_AGENT_AVATAR_LARGE

RUN npm run build

FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist
EXPOSE 5174
CMD ["serve", "-s", "dist", "-l", "5174"]
