FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o dashboard-server .

FROM gcr.io/distroless/static-debian12

WORKDIR /app
COPY --from=builder /app/dashboard-server .

EXPOSE 8081

CMD ["./dashboard-server"]
